/** The Erebus glyph. Geometry is generated by `scripts/brand.py`. */
export function Mark({
  size = 20,
  className,
}: {
  size?: number;
  className?: string;
}) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 256 256"
      aria-hidden="true"
      className={className}
    >
      <defs>
        <clipPath id="erebus-mark-bands">
          <rect x="24" y="24" width="208" height="92" />
          <rect x="24" y="128" width="208" height="34" />
          <rect x="24" y="174" width="208" height="58" />
        </clipPath>
      </defs>
      <path
        fill="currentColor"
        clipPath="url(#erebus-mark-bands)"
        d="M118.11 40.56A88 88 0 1 0 215.44 137.89A74 74 0 0 1 118.11 40.56Z"
      />
    </svg>
  );
}
