import type { Metadata } from "next";
import Image from "next/image";
import { Mark } from "@/components/mark";
import { PageHeader, SectionLabel } from "@/components/page-header";

export const metadata: Metadata = {
  title: "Brand kit — Erebus",
  description:
    "The Erebus mark, wordmark, icon, cover art, and palette, with the few rules that matter.",
};

const assets = [
  {
    name: "Mark",
    file: "/brand/erebus-mark.svg",
    note: "Monochrome, inherits the surrounding text colour",
  },
  {
    name: "Icon",
    file: "/brand/erebus-icon.svg",
    note: "White on the accent square, for avatars and app icons",
  },
  {
    name: "Wordmark",
    file: "/brand/erebus-wordmark.svg",
    note: "Mark plus name, for headers and slides",
  },
  {
    name: "Cover",
    file: "/brand/erebus-cover.png",
    note: "1280×640, for social previews",
  },
];

const palette = [
  { name: "Background", value: "#050506" },
  { name: "Foreground", value: "#e8e6e3" },
  { name: "Muted", value: "#8a8783" },
  { name: "Line", value: "#1c1c1f" },
  { name: "Accent", value: "#b8452b" },
];

export default function BrandPage() {
  return (
    <div className="mx-auto max-w-5xl px-6 py-20 sm:py-28">
      <PageHeader eyebrow="Brand kit" title="An eclipse cut into three bands">
        The disc is still there and almost none of it is legible, which is the
        product. What is left of it is three bands, which are the three mix
        layers. Every asset below is generated by{" "}
        <code className="bg-foreground/5 px-1 py-0.5 font-mono text-[13px] text-foreground">
          scripts/brand.py
        </code>
        , so the geometry cannot drift between them.
      </PageHeader>

      <section className="mt-16">
        <SectionLabel>Marks</SectionLabel>
        <div className="mt-6 grid gap-px bg-line sm:grid-cols-2">
          <div className="flex items-center justify-center bg-background p-14">
            <Mark size={104} className="text-foreground" />
          </div>
          <div className="flex items-center justify-center bg-accent p-14">
            <Mark size={104} className="text-background" />
          </div>
        </div>
      </section>

      <section className="mt-16">
        <SectionLabel>Files</SectionLabel>
        <ul className="mt-6 grid gap-px bg-line sm:grid-cols-2">
          {assets.map((asset) => (
            <li key={asset.file} className="bg-background p-6">
              <div className="flex items-baseline justify-between gap-4">
                <p className="text-[15px]">{asset.name}</p>
                <a
                  href={asset.file}
                  download
                  className="font-mono text-[11px] tracking-[0.14em] uppercase text-accent"
                >
                  Download
                </a>
              </div>
              <p className="mt-2 text-[13px] text-muted">{asset.note}</p>
              <p className="mt-1 font-mono text-[11.5px] text-muted/70">
                {asset.file}
              </p>
            </li>
          ))}
        </ul>
      </section>

      <section className="mt-16">
        <SectionLabel>Cover</SectionLabel>
        <div className="mt-6 border border-line p-4">
          <Image
            src="/brand/erebus-cover.png"
            alt="Erebus cover art: the mark, the name, and the three mix layers"
            width={1280}
            height={640}
            className="h-auto w-full"
          />
        </div>
      </section>

      <section className="mt-16">
        <SectionLabel>Palette</SectionLabel>
        <div className="mt-6 grid gap-px bg-line sm:grid-cols-5">
          {palette.map((colour) => (
            <div key={colour.value} className="bg-background p-5">
              <div
                className="h-16 w-full border border-line"
                style={{ backgroundColor: colour.value }}
              />
              <p className="mt-3 text-[13px]">{colour.name}</p>
              <p className="font-mono text-[11.5px] text-muted">
                {colour.value}
              </p>
            </div>
          ))}
        </div>
      </section>

      <section className="mt-16 border-t border-line pt-10">
        <h2 className="text-xl tracking-tight">Rules</h2>
        <ul className="mt-6 max-w-2xl list-disc space-y-3 pl-5 text-[15px] leading-relaxed text-muted">
          <li>
            Leave clear space around the mark equal to the height of one band.
          </li>
          <li>
            Do not rotate it, add a gradient, outline it, or reorder the bands:
            they are layers, in order.
          </li>
          <li>
            On coloured backgrounds use the accent square rather than placing
            the mark directly on the colour.
          </li>
          <li>
            The mark identifies the project. Do not use it to suggest that
            Erebus endorses, audited, or operates something.
          </li>
        </ul>
      </section>
    </div>
  );
}
