// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

/// @title Groth16 verifier for the Erebus spend circuit.
///
/// @notice Generated by `cargo run --release -p erebus-fees -- export-verifier`
/// and then `forge fmt`. Do not edit: the constants below are the verifying key
/// for the circuit in
/// `mixnet/crates/fees/src/circuit.rs`, derived from the seed in that crate, and
/// a proof only verifies against the key that came out of the same setup.
contract SpendVerifier {
    uint256 private constant P =
        21888242871839275222246405745257275088696311157297823662689037894645226208583;
    uint256 private constant R =
        21888242871839275222246405745257275088548364400416034343698204186575808495617;
    uint256 private constant INPUTS = 3;

    struct G1Point {
        uint256 x;
        uint256 y;
    }

    /// Coordinates of a point over Fp2, imaginary part first, as the pairing
    /// precompile expects them.
    struct G2Point {
        uint256[2] x;
        uint256[2] y;
    }

    error BadInput();
    error BadProof();

    /// @return true when `proof` proves the statement for `input`.
    function verify(uint256[8] calldata proof, uint256[INPUTS] calldata input)
        public
        view
        returns (bool)
    {
        for (uint256 i = 0; i < INPUTS; i++) {
            if (input[i] >= R) revert BadInput();
        }

        G1Point[INPUTS + 1] memory IC;
        IC[0] = G1Point(
            0x02430b34728335c8d10c9ebfdc1ea050a9a7bdf1271b4f2a2befd36f90f59946,
            0x24d2b21450d70491c04cb5ad82e1f6f073c33f3aa751e9cced20dfd64b568b7a
        );
        IC[1] = G1Point(
            0x2b5f9540fab425973d98af1ecdf29a25b51089beb1a623ffdd179ac5163421be,
            0x02ec0eaf6aae0811479251d90c34906709b7ee4c1ad93aca847b19b56f0d8d3b
        );
        IC[2] = G1Point(
            0x2b19b3205c4cfa5793cbcd4faf01f705dfa220b863deb7a7581518514062876b,
            0x0f37c193e77408f178941d9a8008dc233046dff97d0363f74d581798d9ec1fb9
        );
        IC[3] = G1Point(
            0x0b9225831285e02d3b59860c7ebd3781c2dd54ba498773df1edaa16c41d81d57,
            0x26ac0f133539623a82bb74ccb0bba5b3f4a289c5b457cd79d10d6b7b0f93ebde
        );
        G1Point memory vkX = IC[0];
        for (uint256 i = 0; i < INPUTS; i++) {
            vkX = _add(vkX, _mul(IC[i + 1], input[i]));
        }

        G1Point memory a = G1Point(proof[0], proof[1]);
        G2Point memory b = G2Point([proof[2], proof[3]], [proof[4], proof[5]]);
        G1Point memory c = G1Point(proof[6], proof[7]);

        // e(-A, B) * e(alpha, beta) * e(vkX, gamma) * e(C, delta) == 1
        uint256[24] memory pairing;
        _put(pairing, 0, _negate(a), b);
        _put(
            pairing,
            1,
            G1Point(
                0x00d3ea3d7b6ae477b75856546938df2726cdc22a988f706a42bef411c30f0b53,
                0x17beb57bdfb5e3b792135dff8d3c9940417d8cac548ce530b05c3610826c7904
            ),
            G2Point(
                [
                    0x047e285b82ec85b6929e82855fdf3e1c2b53dbc13531a9d8db0abe7538394588,
                    0x190e972bfe4d0c419275bd6b387bc607a665b22aae8f4e0c40a40b392a77576b
                ],
                [
                    0x06f371eb921a6f326e3431a9c65c2702abc49e4359c076545daf275e0b6fc319,
                    0x0a78d5c482d8a103cfb68eb436c07f53a154922da6b8aab4ce191edb6bc05278
                ]
            )
        );
        _put(
            pairing,
            2,
            vkX,
            G2Point(
                [
                    0x1406acb064d5b82479cdc7e89d54c26b4168e7f82ae0a6836700c3632dc87435,
                    0x0458a26a6cab64be678352443140d126160d0b3146909c9e5d4a6780c900577e
                ],
                [
                    0x048f34371a7ddfe3eecbd9dd07051c444d175cd406da0c2f728cc1de1fc856f3,
                    0x25512a7ca6ac4a23aff2364c486e4b1e837b461d1f6a1bd4bf395a19ba41812c
                ]
            )
        );
        _put(
            pairing,
            3,
            c,
            G2Point(
                [
                    0x2a6469ae96722d6ee2f5bc75f451b813ff46bf2aa855b30dd6ce926acb392a65,
                    0x27606320bd86c2e544946e78c1fc065adf08bcc1301d76bd168dfb677cced658
                ],
                [
                    0x0e914ae8da8ac1e16b51bf78a80c3711690bc5c342707443f3245a02770eb41e,
                    0x18d681da89d92bc93f5d527bad510bcd2fa2e00de1a0bf1594db0b57409f1e3c
                ]
            )
        );

        uint256[1] memory out;
        bool ok;
        assembly {
            ok := staticcall(gas(), 8, pairing, 768, out, 32)
        }
        if (!ok) revert BadProof();
        return out[0] == 1;
    }

    function _put(uint256[24] memory into, uint256 slot, G1Point memory p, G2Point memory q)
        private
        pure
    {
        uint256 at = slot * 6;
        into[at] = p.x;
        into[at + 1] = p.y;
        into[at + 2] = q.x[0];
        into[at + 3] = q.x[1];
        into[at + 4] = q.y[0];
        into[at + 5] = q.y[1];
    }

    function _negate(G1Point memory p) private pure returns (G1Point memory) {
        if (p.x == 0 && p.y == 0) return p;
        return G1Point(p.x, P - (p.y % P));
    }

    function _add(G1Point memory a, G1Point memory b) private view returns (G1Point memory out) {
        uint256[4] memory input = [a.x, a.y, b.x, b.y];
        bool ok;
        assembly {
            ok := staticcall(gas(), 6, input, 128, out, 64)
        }
        if (!ok) revert BadProof();
    }

    function _mul(G1Point memory p, uint256 scalar) private view returns (G1Point memory out) {
        uint256[3] memory input = [p.x, p.y, scalar];
        bool ok;
        assembly {
            ok := staticcall(gas(), 7, input, 96, out, 64)
        }
        if (!ok) revert BadProof();
    }
}
